// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYxggZ5si8XdOhyxnUcTW9Lh0LBfPv6JA',
    appId: '1:1019022292458:web:f7d09878eaf45cab5eae93',
    messagingSenderId: '1019022292458',
    projectId: 'mengajarfirebase',
    authDomain: 'mengajarfirebase.firebaseapp.com',
    databaseURL: 'https://mengajarfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mengajarfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6QQmMWqTRYV4Na6IGe9MXqBzVyXMy-mU',
    appId: '1:1019022292458:android:66e6f3650a9a4ee45eae93',
    messagingSenderId: '1019022292458',
    projectId: 'mengajarfirebase',
    databaseURL: 'https://mengajarfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mengajarfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAGfn60-mKGTNfAgFgzqwcsbRa-NMYijY',
    appId: '1:1019022292458:ios:44a8cdac15feb8db5eae93',
    messagingSenderId: '1019022292458',
    projectId: 'mengajarfirebase',
    databaseURL: 'https://mengajarfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mengajarfirebase.firebasestorage.app',
    iosBundleId: 'com.example.myfirstmobileapp',
  );

}